version: "3.8"

services:
  temperance-constellations-api:
    image: temperance-constellations:latest
    container_name: constellations-api
    ports:
     - "8003:8003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ASPNETCORE_URLS: "http://+:8003"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__HistoricalPricesConnection: "Server=host.docker.internal,1433;Database=Historical;User ID=developer;Password=K3n5alr1532025!!;Encrypt=False;TrustServerCertificate=True;"
      AlphaVantageSettings__BaseUrl: "https://www.alphavantage.co/query"
      AlphaVantageSettings__ApiKey: "Q63WJB6QXCD0USO7"
      ConductorSettings__BaseUrl: "http://conductor-api:8002"
      ConnectionStrings__HangfireConnection: "Server=host.docker.internal,1433;Database=TradingBotDb;User ID=developer;Password=K3n5alr1532025!!;Encrypt=False;TrustServerCertificate=True;"
    restart: unless-stopped
networks:
  default:
    external:
      name: temperance_network