services:
  temperance-constellations-api:
    image: temperance-constellations:latest
    container_name: constellations-api
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - nuget-auth
    ports:
      - "8003:8003"
    networks:
      - temperance_network
    environment:
      ASPNETCORE_URLS: "http://+:8003"
      ASPNETCORE_ENVIRONMENT: "Development"
      # Using interpolation to build the strings
      ConnectionStrings__DefaultConnection: "Server=${DB_HOST};Database=TradingBotDb;User ID=${DB_USER};Password=${DB_PASSWORD};Encrypt=False;TrustServerCertificate=${DB_TRUST_CERT};"
      ConnectionStrings__DefaultConnectionString: "Server=${DB_HOST};Database=TradingBotDb;User ID=${DB_USER};Password=${DB_PASSWORD};Encrypt=False;TrustServerCertificate=${DB_TRUST_CERT};"
      ConnectionStrings__HistoricalPricesConnection: "Server=${DB_HOST};Database=Historical;User ID=${DB_USER};Password=${DB_PASSWORD};Encrypt=False;TrustServerCertificate=${DB_TRUST_CERT};"
      ConnectionStrings__HangfireConnection: "Server=${DB_HOST};Database=TradingBotDb;User ID=${DB_USER};Password=${DB_PASSWORD};Encrypt=False;TrustServerCertificate=${DB_TRUST_CERT};"
      
      AlphaVantageSettings__BaseUrl: "https://www.alphavantage.co/query"
      AlphaVantageSettings__ApiKey: "${ALPHA_VANTAGE_API_KEY}"
      ConductorSettings__BaseUrl: "http://conductor-api:8002"
    
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        切实:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

secrets:
  nuget-auth:
    file: ${SECRETS_FILE_PATH}

networks:
  temperance_network:
    external: true